# Archivo de configuración de GitHub Actions
# Automatiza la ejecución del script de noticias cada 5 minutos o manualmente

name: Noticias automáticas   # Nombre visible del workflow en GitHub

on:
  schedule:
      - cron: "0 6 * * *"   # Dispara la acción a las seis de la mañana (formato cron)
  workflow_dispatch:           # Permite ejecutarlo manualmente desde la interfaz de GitHub

jobs:
  run:                         # Define el trabajo principal
    runs-on: ubuntu-latest     # Usa un contenedor Ubuntu como entorno

    steps:
      - uses: actions/checkout@v4          # Descarga el código del repositorio
      - uses: actions/setup-python@v5      # Instala Python
        with:
          python-version: "3.12"           # Versión específica de Python

      - run: pip install -r requirements.txt  # Instala dependencias del proyecto

      - name: Ejecutar recolector
        env:
          SMTP_PASS: ${{ secrets.SMTP_PASS }} # hhsf jleh rmix rvof
        run: python marca_harvester.py        # Ejecuta el script principal que recoge las noticias
